version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password4
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: Password4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
