services:
  spring-boot-camel-k8s:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - camel-network

  camel-karavan:
    image: ghcr.io/apache/camel-karavan:latest
    container_name: camel-karavan
    ports:
      - "8081:8080"
    networks:
      - camel-network

networks:
  camel-network:
    driver: bridge