services:
  spring-boot-camel-k8s:
    container_name: api-proc
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - camel-network

  camel-karavan:
    image: ghcr.io/apache/camel-karavan:latest
    container_name: camel-karavan
    volumes:
      - C:\Users\sheel\IdeaProjects\spring-boot-examples\apache-camel\spring-boot-camel-k8s\input:/input # Mount host directory to container
    ports:
      - "8081:8080"
    environment:
      - KAMELEON=true # Enable Camel K integration
    networks:
      - camel-network

networks:
  camel-network:
    driver: bridge