services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    restart: always

volumes:
  registry-data: 
    driver: local
    driver_opts:
      type: none
      device: c:\Users\sheel\registry-data
      o: bind