apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  name: test
spec:
  flows:
    - from:
        parameters:
          period: "1000"
        steps:
          - setBody:
              simple: Hello Camel from ${routeId}
          - log: ${body}
        uri: timer:yaml