apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-camel-config
data:
  application.yml: |
    server:
      port: 8080
    spring:
      camel:
        context:
          auto-startup: true
  logback-spring.xml: |
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss} - %msg%n</pattern>
        </encoder>
      </appender>
      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>