apiVersion: v1
kind: Service
metadata:
  name: spring-boot-camel-service
  labels:
    app: spring-boot-camel
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-camel