apiVersion: v1
kind: Namespace
metadata:
  name: redis-namespace

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: springboot-example
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: redis
          args: ["--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: redis-volume
              mountPath: /redis-data
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: redis-volume
          emptyDir:
            sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: redis-namespace
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079
  selector:
    app: redis