apiVersion: v1
kind: Service
metadata:
  name: springboot-camel-play
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: springboot-camel-play

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-camel-play
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-camel-play
  template:
    metadata:
      labels:
        app: springboot-camel-play
    spec:
      containers:
        - name: springboot-camel-play
          image: host.docker.internal:5000/springboot-camel-play:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.mysql-namespace.svc.cluster.local:3306/{{ .Values.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: app_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: Password$4