spring:
  datasource:
    url: jdbc:postgresql://192.168.1.19:5432/testdb
    username: testuser
    password: Password$4
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update